# -*- coding: utf-8 -*-
"""Correlation_Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qw8Bg1SRN8ZmA28OuiGvur8Keq5UrXF6
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
df = pd.read_csv("cleaned_stock_prices.csv")
for col in df.columns:
    df[col] = pd.to_numeric(df[col].astype(str).str.replace(',', ''), errors='coerce')
corr_matrix = df.corr(numeric_only=True)
print("Correlation Matrix:\n", corr_matrix, "\n")
target_corr = corr_matrix['Price'].sort_values(ascending=False)
print("Correlation with 'Price':\n", target_corr, "\n")
top_features = target_corr.drop('Price').head(3)
print("Top 3 features most related to 'Price':\n", top_features)
plt.figure(figsize=(8,5))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap (All Numeric Features)')
plt.show()
print("\n📊 Report: Key Predictive Variables")
print("The correlation analysis helps us identify which numeric features "
      "move in the same direction as the target variable (price movement).")
print("These variables are likely to be the strongest predictors for stock price movement "
      "and can be prioritized in further modeling steps.")
print("\n✅ Milestone Achieved: Key predictive variables identified.")

import zipfile

with zipfile.ZipFile('EDA_outputs.zip', 'w') as zipf:
    corr_matrix.to_csv("correlation_matrix.csv")
    zipf.write("correlation_matrix.csv")

    plt.figure(figsize=(8,5))
    sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
    plt.title('Correlation Heatmap (All Numeric Features)')
    plt.savefig("correlation_heatmap.png")
    zipf.write("correlation_heatmap.png")

from google.colab import files
files.download('EDA_outputs.zip')