# -*- coding: utf-8 -*-
"""Processed_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14iUafIfqyErSJm8Al22es2KIn15htCfb
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
df = pd.read_csv("Microsoft_Stock_Price_History.csv")
print("----- BEFORE CLEANING -----")
print(df.info())
print("\nMissing values before cleaning:\n", df.isnull().sum())
print("\nDuplicate rows before cleaning:", df.duplicated().sum())
print("\nSummary statistics before cleaning:\n", df.describe())
before_rows = df.shape[0]
before_missing = df.isnull().sum().sum()
before_duplicates = df.duplicated().sum()
df = df.drop_duplicates()
df = df.ffill().bfill()
numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    df[col] = np.where(df[col] < lower, lower,
                       np.where(df[col] > upper, upper, df[col]))
print("\n----- AFTER CLEANING -----")
print(df.info())
print("\nMissing values after cleaning:\n", df.isnull().sum())
print("\nDuplicate rows after cleaning:", df.duplicated().sum())
print("\nSummary statistics after cleaning:\n", df.describe())
after_rows = df.shape[0]
after_missing = df.isnull().sum().sum()
after_duplicates = df.duplicated().sum()

# Save cleaned dataset
df.to_csv("cleaned_stock_prices.csv", index=False)
print("\n✅ Cleaned dataset saved as cleaned_stock_prices.csv")

# =============== BEFORE vs AFTER REPORT ===============
comparison = pd.DataFrame({
    "Aspect": ["Total Rows", "Missing Values", "Duplicate Rows"],
    "Before Cleaning": [before_rows, before_missing, before_duplicates],
    "After Cleaning": [after_rows, after_missing, after_duplicates]
})

print("\n--- BEFORE vs AFTER CLEANING REPORT ---\n")
print(comparison)

from google.colab import files

# Save DataFrame to CSV
df.to_csv('cleaned_stock_prices.csv', index=False)

# Download the CSV file
files.download('cleaned_stock_prices.csv')